name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: windows-latest

    steps:
    - uses: actions/checkout@v1

    - uses: msys2/setup-msys2@v2

    - shell: msys2 {0}
      name: Install secp256k1 (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        ./autogen.sh
        ./configure --prefix=/usr --enable-module-schnorrsig --enable-experimental
        make
        make check
        make install
