name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v1

    - uses: msys2/setup-msys2@v2

    - shell: msys2 {0}
      name: Installing tools
      run: |
        # pacman -S --noconfirm autoconf automake base-devel gcc libtool
        pacman -S --noconfirm autoconf automake base-devel mingw-w64-x86_64-toolchain libtool

    - shell: msys2 {0}
      name: Configure secp256k1
      run: |
        ./autogen.sh
        ./configure --prefix=/usr --enable-module-schnorrsig --enable-experimental
        # --disable-dependency-tracking

    - shell: msys2 {0}
      name: Build
      run: |
        make

    - shell: msys2 {0}
      name: Test
      run: |
        make check

    - shell: msys2 {0}
      name: Install
      run: |
        make install
