name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install pkgconfiglite (Windows)
      if: matrix.os == 'windows-latest'
      run: choco install -y pkgconfiglite

    - name: Install secp256k1 (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get -y install autoconf automake libtool
        ./autogen.sh
        ./configure --prefix=/usr --enable-module-schnorrsig --enable-experimental
        make
        make check
        sudo make install
        cd ../..

    - name: Install autoconf (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        curl http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz -o autoconf-2.69.tar.gz
        tar zxvf autoconf-2.69.tar.gz
        cd autoconf-2.69/
        make
        make install

    - name: Install secp256k1 (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        ./autogen.sh
        ./configure --prefix=/usr --enable-module-schnorrsig --enable-experimental
        make
        make check
        make install
