name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v1

    - uses: msys2/setup-msys2@v2

    - shell: msys2 {0}
      name: Install secp256k1 (Windows)
      run: |
        pacman -S --noconfirm autoconf autotools
        ./autogen.sh
        ./configure --prefix=/usr --enable-module-schnorrsig --enable-experimental
        make
        make check
        make install
